---
include:
  - board: xiao_ble
    shield: zonkey_L
    snippet: zmk-usb-logging studio-rpc-usb-uart zonkey_JIS
    artifact-name: zonkey_L_JIS

  - board: xiao_ble
    shield: zonkey_R
    snippet: zmk-usb-logging studio-rpc-usb-uart zonkey_JIS
    artifact-name: zonkey_R_JIS

  - board: xiao_ble
    shield: settings_reset
